name: build
on: push
jobs:
  build-default:
    runs-on: ubuntu-latest
    container:
      image: nixos/nix
    steps:
      - uses: actions/checkout@v3
      - run: pwd
      - run: ls -lah
      - run: nix-build
    
