# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: build
on: push
jobs:
  build-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: cachix/install-nix-action@v18
        with:
          nix_path: nixpkgs=channel:nixos-22.11

      - run: nix-build -A dailykaenguru-layeredImage

      - run: podman load -i ${{ github.workspace }}/result

      - run: echo "image_tag=$(podman images dailykaenguru --format '{{ .Tag }}')" >> $GITHUB_ENV

      - uses: redhat-actions/push-to-registry@v2
        with:
          registry: ghcr.io/jvytee
          image: dailykaenguru
          tags: ${{ env.image_tag }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/upload-artifact@v3
        with:
          name: dailykaenguru-image-x86_64
          path: ${{ github.workspace }}/result
