name: build
on: push
jobs:
  build-default:
    runs-on: ubuntu-latest
    container:
      image: nixos/nix
    steps:
      - run: nix-build https://github.com/jvytee/dailykaenguru/archive/main.tar.gz
      - uses: actions/upload-artifact@v3
        with:
          name: dailykaenguru-image-x86_64
          path: result
