name: build
on: push
jobs:
  build-default:
    runs-on: ubuntu-latest
    steps:
      - uses: cachix/install-nix-action@v17
        with:
          nix_path: nixpkgs=channel:nixos-21.11
      - run: nix-build https://github.com/jvytee/dailykaenguru/archive/main.tar.gz
      - uses: actions/upload-artifact@v3
        with:
          name: dailykaenguru-image-x86_64
          path: ${{ github.workspace}}/result
